class Idioma:

    ATUAL = "pt"

    TEXTOS = {
        "pt": {

            # Comuns a várias telas
            "comum.id": "ID",
            "comum.nome": "Nome",
            "comum.novo": "Novo",
            "comum.salvar": "Salvar",
            "comum.alterar": "Alterar",
            "comum.excluir": "Excluir",
            "comum.fechar": "Fechar",
            "comum.cancelar": "Cancelar",
            "comum.confirmacao": "Confirmação",
            "comum.erro_prefixo": "Erro: ",
            "comum.selecione": "Selecione...",

            # Tela principal / App
            "app_titulo": "ZELADOC",

            "menu_pacientes": "Pacientes",
            "menu_medicos": "Médicos",
            "menu_consultas": "Consultas",
            "menu_usuarios": "Usuários",
            "menu_convenios": "Convênios",
            "menu_especialidades": "Especialidades",
            "menu_exames": "Exames",
            "menu_prontuarios": "Prontuários",
            "menu_sair": "Sair",
            "menu_idioma": "English",

            # Tela de Convênios
            "convenio.janela_titulo": "CRUD de Convênios",
            "convenio.titulo": "Cadastro de Convênio",
            "convenio.dados_frame": "Dados do convênio",
            "convenio.confirmar_exclusao": "Deseja realmente excluir este convênio?",
            "convenio.cadastrado_sucesso": "Convênio cadastrado com sucesso!",
            "convenio.atualizado_sucesso": "Convênio atualizado com sucesso!",
            "convenio.excluido_sucesso": "Convênio excluído com sucesso!",
            "convenio.nao_encontrado": "Convênio não encontrado.",
            "convenio.selecione_da_lista": "Selecione um convênio na lista.",
            "convenio.erro_ao_excluir": "Problemas ao excluir convênio",
            "convenio.erro_possui_vinculos": "Não é possível excluir: existem pacientes vinculados a este convênio.",
            "convenio.erro_nome_vazio": "O nome do convênio não pode ficar vazio.",

            # Tela de Especialidades
            "especialidade.janela_titulo": "CRUD de Especialidades",
            "especialidade.titulo": "Cadastro de Especialidade",
            "especialidade.dados_frame": "Dados da especialidade",
            "especialidade.confirmar_exclusao": "Deseja realmente excluir esta especialidade?",
            "especialidade.cadastrado_sucesso": "Especialidade cadastrada com sucesso!",
            "especialidade.atualizado_sucesso": "Especialidade atualizada com sucesso!",
            "especialidade.excluido_sucesso": "Especialidade excluída com sucesso!",
            "especialidade.nao_encontrado": "Especialidade não encontrada.",
            "especialidade.selecione_da_lista": "Selecione uma especialidade na lista.",
            "especialidade.erro_ao_excluir": "Problemas ao excluir especialidade",
            "especialidade.erro_possui_vinculos": "Não é possível excluir: existem médicos vinculados a esta especialidade.",
            "especialidade.erro_nome_vazio": "O nome da especialidade não pode ficar vazio.",

            # Tela de Exames
            "exame.janela_titulo": "CRUD de Exames",
            "exame.titulo": "Cadastro de Exame",
            "exame.dados_frame": "Dados do exame",
            "exame.confirmar_exclusao": "Deseja realmente excluir este exame?",
            "exame.cadastrado_sucesso": "Exame cadastrado com sucesso!",
            "exame.atualizado_sucesso": "Exame atualizado com sucesso!",
            "exame.excluido_sucesso": "Exame excluído com sucesso!",
            "exame.nao_encontrado": "Exame não encontrado.",
            "exame.selecione_da_lista": "Selecione um exame na lista.",
            "exame.erro_ao_excluir": "Problemas ao excluir exame",
            "exame.erro_nome_vazio": "O nome do exame não pode ficar vazio.",

            # Tela de Usuários
            "usuario.janela_titulo": "CRUD de Usuários",
            "usuario.titulo": "Cadastro de Usuário",
            "usuario.dados_frame": "Dados do usuário",
            "usuario.email": "Email",
            "usuario.senha": "Senha",
            "usuario.confirmar_exclusao": "Deseja realmente excluir este usuário?",
            "usuario.cadastrado_sucesso": "Usuário cadastrado com sucesso!",
            "usuario.atualizado_sucesso": "Usuário atualizado com sucesso!",
            "usuario.excluido_sucesso": "Usuário excluído com sucesso!",
            "usuario.nao_encontrado": "Usuário não encontrado.",
            "usuario.selecione_da_lista": "Selecione um usuário na lista.",
            "usuario.erro_ao_excluir": "Problemas ao excluir usuário",
            "usuario.erro_possui_vinculos": "Não é possível excluir: existe um médico vinculado a este usuário.",
            "usuario.erro_nome_vazio": "O nome do usuário não pode ficar vazio.",
            "usuario.erro_email_vazio": "O email do usuário não pode ficar vazio.",
            "usuario.erro_senha_vazia": "Informe uma senha para o novo usuário.",

            # Tela de Médicos
            "medico.janela_titulo": "CRUD de Médicos",
            "medico.titulo": "Cadastro de Médico",
            "medico.dados_frame": "Dados do médico",
            "medico.crm": "CRM",
            "medico.especialidade": "Especialidade",
            "medico.usuario": "Usuário (login)",
            "medico.confirmar_exclusao": "Deseja realmente excluir este médico?",
            "medico.cadastrado_sucesso": "Médico cadastrado com sucesso!",
            "medico.atualizado_sucesso": "Médico atualizado com sucesso!",
            "medico.excluido_sucesso": "Médico excluído com sucesso!",
            "medico.nao_encontrado": "Médico não encontrado.",
            "medico.selecione_da_lista": "Selecione um médico na lista.",
            "medico.erro_ao_excluir": "Problemas ao excluir médico",
            "medico.erro_nome_vazio": "O nome do médico não pode ficar vazio.",
            "medico.erro_crm_vazio": "Informe o CRM do médico.",
            "medico.erro_especialidade_nao_selecionada": "Selecione uma especialidade para o médico.",
            "medico.erro_usuario_nao_selecionado": "Selecione um usuário (login) para o médico.",

            # Tela de Pacientes
            "paciente.janela_titulo": "CRUD de Pacientes",
            "paciente.titulo": "Cadastro de Paciente",
            "paciente.dados_frame": "Dados do paciente",
            "paciente.dados_endereco_frame": "Endereço",
            "paciente.nascimento": "Data de nascimento (DD/MM/AAAA)",
            "paciente.idade": "Idade",
            "paciente.convenio": "Convênio",
            "paciente.logradouro": "Logradouro",
            "paciente.numero": "Número",
            "paciente.cidade": "Cidade",
            "paciente.uf": "UF",
            "paciente.confirmar_exclusao": "Deseja realmente excluir este paciente?",
            "paciente.cadastrado_sucesso": "Paciente cadastrado com sucesso!",
            "paciente.atualizado_sucesso": "Paciente atualizado com sucesso!",
            "paciente.excluido_sucesso": "Paciente excluído com sucesso!",
            "paciente.nao_encontrado": "Paciente não encontrado.",
            "paciente.selecione_da_lista": "Selecione um paciente na lista.",
            "paciente.erro_ao_excluir": "Problemas ao excluir paciente",
            "paciente.erro_nome_vazio": "O nome do paciente não pode ficar vazio.",
            "paciente.erro_data_invalida": "Data de nascimento inválida. Use o formato DD/MM/AAAA.",
            "paciente.erro_convenio_nao_selecionado": "Selecione um convênio para o paciente.",
            "paciente.erro_numero_invalido": "O número do endereço deve ser um valor numérico.",

            # Tela de Consultas
            "consulta.janela_titulo": "CRUD de Consultas",
            "consulta.titulo": "Agendamento de Consulta",
            "consulta.dados_frame": "Dados da consulta",
            "consulta.paciente": "Paciente",
            "consulta.medico": "Médico",
            "consulta.data_hora": "Data e hora (DD/MM/AAAA HH:MM)",
            "consulta.confirmar_exclusao": "Deseja realmente excluir esta consulta?",
            "consulta.cadastrado_sucesso": "Consulta agendada com sucesso!",
            "consulta.atualizado_sucesso": "Consulta atualizada com sucesso!",
            "consulta.excluido_sucesso": "Consulta excluída com sucesso!",
            "consulta.nao_encontrado": "Consulta não encontrada.",
            "consulta.selecione_da_lista": "Selecione uma consulta na lista.",
            "consulta.erro_ao_excluir": "Problemas ao excluir consulta",
            "consulta.erro_data_invalida": "Data e hora inválidas. Use o formato DD/MM/AAAA HH:MM.",
            "consulta.erro_paciente_nao_selecionado": "Selecione um paciente para a consulta.",
            "consulta.erro_medico_nao_selecionado": "Selecione um médico para a consulta.",

            # Tela de Prontuários
            "prontuario.janela_titulo": "CRUD de Prontuários",
            "prontuario.titulo": "Cadastro de Prontuário",
            "prontuario.dados_frame": "Dados do prontuário",
            "prontuario.paciente": "Paciente",
            "prontuario.observacoes": "Observações",
            "prontuario.confirmar_exclusao": "Deseja realmente excluir este prontuário?",
            "prontuario.cadastrado_sucesso": "Prontuário cadastrado com sucesso!",
            "prontuario.atualizado_sucesso": "Prontuário atualizado com sucesso!",
            "prontuario.excluido_sucesso": "Prontuário excluído com sucesso!",
            "prontuario.nao_encontrado": "Prontuário não encontrado.",
            "prontuario.selecione_da_lista": "Selecione um prontuário na lista.",
            "prontuario.erro_ao_excluir": "Problemas ao excluir prontuário",
            "prontuario.erro_observacoes_vazias": "As observações não podem ficar vazias.",
            "prontuario.erro_paciente_nao_selecionado": "Selecione um paciente para o prontuário.",
        },
        "en": {

            # Common to several screens
            "comum.id": "ID",
            "comum.nome": "Name",
            "comum.novo": "New",
            "comum.salvar": "Save",
            "comum.alterar": "Edit",
            "comum.excluir": "Delete",
            "comum.fechar": "Close",
            "comum.cancelar": "Cancel",
            "comum.confirmacao": "Confirmation",
            "comum.erro_prefixo": "Error: ",
            "comum.selecione": "Select...",

            # Main screen / App
            "app_titulo": "ZELADOC",

            "menu_pacientes": "Patients",
            "menu_medicos": "Doctors",
            "menu_consultas": "Appointments",
            "menu_usuarios": "Users",
            "menu_convenios": "Insurance Plans",
            "menu_especialidades": "Specialties",
            "menu_exames": "Exams",
            "menu_prontuarios": "Medical Records",
            "menu_sair": "Exit",
            "menu_idioma": "Português",

            # Insurance plans screen
            "convenio.janela_titulo": "Insurance Plan Management",
            "convenio.titulo": "Insurance Plan Registration",
            "convenio.dados_frame": "Insurance plan data",
            "convenio.confirmar_exclusao": "Do you really want to delete this insurance plan?",
            "convenio.cadastrado_sucesso": "Insurance plan registered successfully!",
            "convenio.atualizado_sucesso": "Insurance plan updated successfully!",
            "convenio.excluido_sucesso": "Insurance plan deleted successfully!",
            "convenio.nao_encontrado": "Insurance plan not found.",
            "convenio.selecione_da_lista": "Select an insurance plan from the list.",
            "convenio.erro_ao_excluir": "Problem deleting insurance plan",
            "convenio.erro_possui_vinculos": "Cannot delete: there are patients linked to this insurance plan.",
            "convenio.erro_nome_vazio": "The insurance plan name cannot be empty.",

            # Specialties screen
            "especialidade.janela_titulo": "Specialty Management",
            "especialidade.titulo": "Specialty Registration",
            "especialidade.dados_frame": "Specialty data",
            "especialidade.confirmar_exclusao": "Do you really want to delete this specialty?",
            "especialidade.cadastrado_sucesso": "Specialty registered successfully!",
            "especialidade.atualizado_sucesso": "Specialty updated successfully!",
            "especialidade.excluido_sucesso": "Specialty deleted successfully!",
            "especialidade.nao_encontrado": "Specialty not found.",
            "especialidade.selecione_da_lista": "Select a specialty from the list.",
            "especialidade.erro_ao_excluir": "Problem deleting specialty",
            "especialidade.erro_possui_vinculos": "Cannot delete: there are doctors linked to this specialty.",
            "especialidade.erro_nome_vazio": "The specialty name cannot be empty.",

            # Exams screen
            "exame.janela_titulo": "Exam Management",
            "exame.titulo": "Exam Registration",
            "exame.dados_frame": "Exam data",
            "exame.confirmar_exclusao": "Do you really want to delete this exam?",
            "exame.cadastrado_sucesso": "Exam registered successfully!",
            "exame.atualizado_sucesso": "Exam updated successfully!",
            "exame.excluido_sucesso": "Exam deleted successfully!",
            "exame.nao_encontrado": "Exam not found.",
            "exame.selecione_da_lista": "Select an exam from the list.",
            "exame.erro_ao_excluir": "Problem deleting exam",
            "exame.erro_nome_vazio": "The exam name cannot be empty.",

            # Users screen
            "usuario.janela_titulo": "User Management",
            "usuario.titulo": "User Registration",
            "usuario.dados_frame": "User data",
            "usuario.email": "Email",
            "usuario.senha": "Password",
            "usuario.confirmar_exclusao": "Do you really want to delete this user?",
            "usuario.cadastrado_sucesso": "User registered successfully!",
            "usuario.atualizado_sucesso": "User updated successfully!",
            "usuario.excluido_sucesso": "User deleted successfully!",
            "usuario.nao_encontrado": "User not found.",
            "usuario.selecione_da_lista": "Select a user from the list.",
            "usuario.erro_ao_excluir": "Problem deleting user",
            "usuario.erro_possui_vinculos": "Cannot delete: there is a doctor linked to this user.",
            "usuario.erro_nome_vazio": "The user name cannot be empty.",
            "usuario.erro_email_vazio": "The user email cannot be empty.",
            "usuario.erro_senha_vazia": "Enter a password for the new user.",

            # Doctors screen
            "medico.janela_titulo": "Doctor Management",
            "medico.titulo": "Doctor Registration",
            "medico.dados_frame": "Doctor data",
            "medico.crm": "License (CRM)",
            "medico.especialidade": "Specialty",
            "medico.usuario": "User (login)",
            "medico.confirmar_exclusao": "Do you really want to delete this doctor?",
            "medico.cadastrado_sucesso": "Doctor registered successfully!",
            "medico.atualizado_sucesso": "Doctor updated successfully!",
            "medico.excluido_sucesso": "Doctor deleted successfully!",
            "medico.nao_encontrado": "Doctor not found.",
            "medico.selecione_da_lista": "Select a doctor from the list.",
            "medico.erro_ao_excluir": "Problem deleting doctor",
            "medico.erro_nome_vazio": "The doctor name cannot be empty.",
            "medico.erro_crm_vazio": "Enter the doctor's license (CRM).",
            "medico.erro_especialidade_nao_selecionada": "Select a specialty for the doctor.",
            "medico.erro_usuario_nao_selecionado": "Select a user (login) for the doctor.",

            # Patients screen
            "paciente.janela_titulo": "Patient Management",
            "paciente.titulo": "Patient Registration",
            "paciente.dados_frame": "Patient data",
            "paciente.dados_endereco_frame": "Address",
            "paciente.nascimento": "Date of birth (DD/MM/YYYY)",
            "paciente.idade": "Age",
            "paciente.convenio": "Insurance Plan",
            "paciente.logradouro": "Street",
            "paciente.numero": "Number",
            "paciente.cidade": "City",
            "paciente.uf": "State",
            "paciente.confirmar_exclusao": "Do you really want to delete this patient?",
            "paciente.cadastrado_sucesso": "Patient registered successfully!",
            "paciente.atualizado_sucesso": "Patient updated successfully!",
            "paciente.excluido_sucesso": "Patient deleted successfully!",
            "paciente.nao_encontrado": "Patient not found.",
            "paciente.selecione_da_lista": "Select a patient from the list.",
            "paciente.erro_ao_excluir": "Problem deleting patient",
            "paciente.erro_nome_vazio": "The patient name cannot be empty.",
            "paciente.erro_data_invalida": "Invalid date of birth. Use the DD/MM/YYYY format.",
            "paciente.erro_convenio_nao_selecionado": "Select an insurance plan for the patient.",
            "paciente.erro_numero_invalido": "The address number must be numeric.",

            # Appointments screen
            "consulta.janela_titulo": "Appointment Management",
            "consulta.titulo": "Appointment Scheduling",
            "consulta.dados_frame": "Appointment data",
            "consulta.paciente": "Patient",
            "consulta.medico": "Doctor",
            "consulta.data_hora": "Date and time (DD/MM/YYYY HH:MM)",
            "consulta.confirmar_exclusao": "Do you really want to delete this appointment?",
            "consulta.cadastrado_sucesso": "Appointment scheduled successfully!",
            "consulta.atualizado_sucesso": "Appointment updated successfully!",
            "consulta.excluido_sucesso": "Appointment deleted successfully!",
            "consulta.nao_encontrado": "Appointment not found.",
            "consulta.selecione_da_lista": "Select an appointment from the list.",
            "consulta.erro_ao_excluir": "Problem deleting appointment",
            "consulta.erro_data_invalida": "Invalid date and time. Use the DD/MM/YYYY HH:MM format.",
            "consulta.erro_paciente_nao_selecionado": "Select a patient for the appointment.",
            "consulta.erro_medico_nao_selecionado": "Select a doctor for the appointment.",

            # Medical records screen
            "prontuario.janela_titulo": "Medical Record Management",
            "prontuario.titulo": "Medical Record Registration",
            "prontuario.dados_frame": "Medical record data",
            "prontuario.paciente": "Patient",
            "prontuario.observacoes": "Notes",
            "prontuario.confirmar_exclusao": "Do you really want to delete this medical record?",
            "prontuario.cadastrado_sucesso": "Medical record registered successfully!",
            "prontuario.atualizado_sucesso": "Medical record updated successfully!",
            "prontuario.excluido_sucesso": "Medical record deleted successfully!",
            "prontuario.nao_encontrado": "Medical record not found.",
            "prontuario.selecione_da_lista": "Select a medical record from the list.",
            "prontuario.erro_ao_excluir": "Problem deleting medical record",
            "prontuario.erro_observacoes_vazias": "The notes cannot be empty.",
            "prontuario.erro_paciente_nao_selecionado": "Select a patient for the medical record.",
        }
    }

    @classmethod
    def definir(cls, codigo):
        cls.ATUAL = codigo

    @classmethod
    def t(cls, chave):
        return cls.TEXTOS[cls.ATUAL].get(chave, chave)


def t(chave):
    return Idioma.t(chave)


def trocar_idioma():
    Idioma.definir("en" if Idioma.ATUAL == "pt" else "pt")